parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $redis: '@snc_redis.default'
    _instanceof:
        App\Model\RedisStorageInterface:
            tags: [ 'app.redis_storage' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\ParamConverter\RedisParamConverter:
        arguments:
            - !tagged_iterator app.redis_storage
